-- schema_v61.sql -- Device Batch purchase reliability and audit trail.
-- Additive except for replacing the v59 inventory trigger function with a
-- symmetric delta implementation.

alter table public.voyager_orders
  add column if not exists checkout_expires_at timestamptz;

create index if not exists voyager_orders_pending_checkout_expiry_idx
  on public.voyager_orders (checkout_expires_at)
  where product_type = 'device_batch_claim'
    and status = 'pending'
    and checkout_expires_at is not null;

create table if not exists public.stripe_webhook_events (
  event_id          text primary key,
  event_type        text not null,
  status            text not null default 'processing',
  attempt_count     integer not null default 1,
  event_created_at  timestamptz,
  last_error        text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  processed_at      timestamptz
);

alter table public.stripe_webhook_events
  drop constraint if exists stripe_webhook_events_status_check;
alter table public.stripe_webhook_events
  add constraint stripe_webhook_events_status_check
  check (status in ('processing', 'processed', 'failed'));

alter table public.stripe_webhook_events enable row level security;
revoke all on public.stripe_webhook_events from anon, authenticated;
grant select, insert, update, delete on public.stripe_webhook_events to service_role;

create table if not exists public.device_order_status_events (
  id          bigint generated by default as identity primary key,
  order_id    uuid not null references public.voyager_orders(id) on delete cascade,
  old_status  text,
  new_status  text not null,
  changed_at  timestamptz not null default now()
);

create index if not exists device_order_status_events_order_idx
  on public.device_order_status_events (order_id, changed_at desc);

alter table public.device_order_status_events enable row level security;
revoke all on public.device_order_status_events from anon, authenticated;
grant select, insert, update, delete on public.device_order_status_events to service_role;
grant usage, select on sequence public.device_order_status_events_id_seq to service_role;

create or replace function public.claim_stripe_webhook_event(
  p_event_id text,
  p_event_type text,
  p_event_created_at timestamptz default null
)
returns text
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  acquired text;
  current_status text;
begin
  insert into public.stripe_webhook_events (
    event_id,
    event_type,
    event_created_at
  )
  values (
    p_event_id,
    p_event_type,
    p_event_created_at
  )
  on conflict (event_id) do update
    set status = 'processing',
        attempt_count = public.stripe_webhook_events.attempt_count + 1,
        last_error = null,
        updated_at = now()
    where public.stripe_webhook_events.status = 'failed'
      or (
        public.stripe_webhook_events.status = 'processing'
        and public.stripe_webhook_events.updated_at < now() - interval '5 minutes'
      )
  returning 'claimed' into acquired;

  if acquired is not null then
    return acquired;
  end if;

  select status
    into current_status
    from public.stripe_webhook_events
    where event_id = p_event_id;

  if current_status = 'processed' then
    return 'processed';
  end if;
  return 'busy';
end;
$$;

revoke all on function public.claim_stripe_webhook_event(text, text, timestamptz)
  from public;
grant execute on function public.claim_stripe_webhook_event(text, text, timestamptz)
  to service_role;

create or replace function public.log_device_order_status_change()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.device_order_status_events (order_id, old_status, new_status)
  values (new.id, case when tg_op = 'INSERT' then null else old.status end, new.status);
  return new;
end;
$$;

revoke all on function public.log_device_order_status_change() from public;

drop trigger if exists voyager_orders_device_status_audit
  on public.voyager_orders;
drop trigger if exists voyager_orders_device_status_audit_insert
  on public.voyager_orders;
drop trigger if exists voyager_orders_device_status_audit_update
  on public.voyager_orders;

create trigger voyager_orders_device_status_audit_insert
after insert on public.voyager_orders
for each row
when (new.product_type = 'device_batch_claim')
execute function public.log_device_order_status_change();

create trigger voyager_orders_device_status_audit_update
after update of status on public.voyager_orders
for each row
when (
  new.product_type = 'device_batch_claim'
  and old.status is distinct from new.status
)
execute function public.log_device_order_status_change();

create or replace function public.manage_device_batch_inventory()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  batch_record public.device_batches%rowtype;
  old_reserved boolean := false;
  new_reserved boolean;
  old_claimed boolean := false;
  new_claimed boolean;
  reserved_delta integer;
  claimed_delta integer;
  total_delta integer;
begin
  if new.product_type is distinct from 'device_batch_claim' then
    return new;
  end if;

  if tg_op = 'UPDATE'
    and (
      old.product_type is distinct from new.product_type
      or old.device_batch_slug is distinct from new.device_batch_slug
    ) then
    raise exception 'Device Batch order identity cannot be changed';
  end if;

  select *
    into batch_record
    from public.device_batches
    where slug = new.device_batch_slug
    for update;

  if not found then
    raise exception 'Device Batch is not published in inventory';
  end if;

  new_reserved := new.status in ('pending', 'payment_review');
  new_claimed := new.status in ('paid', 'preparing', 'shipped', 'delivered');

  if tg_op = 'INSERT' then
    if new.status <> 'pending' then
      raise exception 'New Device Batch claims must start pending';
    end if;
  else
    old_reserved := old.status in ('pending', 'payment_review');
    old_claimed := old.status in ('paid', 'preparing', 'shipped', 'delivered');
  end if;

  reserved_delta := new_reserved::integer - old_reserved::integer;
  claimed_delta := new_claimed::integer - old_claimed::integer;
  total_delta := reserved_delta + claimed_delta;

  if total_delta > 0 then
    if batch_record.publication_status <> 'published'
      or batch_record.device_status <> 'claim_open' then
      raise exception 'Device Batch claims are not open';
    end if;
    if batch_record.claimed_quantity
      + batch_record.reserved_quantity
      + total_delta
      > batch_record.listing_quantity then
      raise exception 'Device Batch is fully claimed';
    end if;
  end if;

  if batch_record.reserved_quantity + reserved_delta < 0
    or batch_record.claimed_quantity + claimed_delta < 0 then
    raise exception 'Device Batch inventory transition is inconsistent';
  end if;

  if reserved_delta <> 0 or claimed_delta <> 0 then
    update public.device_batches
      set reserved_quantity = reserved_quantity + reserved_delta,
          claimed_quantity = claimed_quantity + claimed_delta,
          updated_at = now()
      where id = batch_record.id;
  end if;

  return new;
end;
$$;

revoke all on function public.manage_device_batch_inventory() from public;
