-- schema_v59.sql — code-driven personalized push campaigns
-- Additive and idempotent. Run after schema_v58.sql.

alter table public.push_preferences
  add column if not exists announcements boolean not null default true;

create table if not exists public.push_campaigns (
  id uuid primary key default gen_random_uuid(),
  campaign_key text not null unique,
  spec_hash text not null,
  title_template text not null,
  body_template text not null,
  route_template text not null,
  audience jsonb not null default '{}'::jsonb,
  variables jsonb not null default '{}'::jsonb,
  status text not null default 'draft'
    check (status in ('draft', 'queued', 'sending', 'completed', 'failed', 'cancelled')),
  requested_by uuid references public.voyager_profiles(id) on delete set null,
  requested_by_label text not null default 'unknown',
  test_user_id uuid references public.voyager_profiles(id) on delete set null,
  test_delivered_at timestamptz,
  total_recipients integer not null default 0,
  sent_recipients integer not null default 0,
  failed_recipients integer not null default 0,
  skipped_recipients integer not null default 0,
  created_at timestamptz not null default now(),
  queued_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.push_campaigns(id) on delete cascade,
  user_id uuid not null references public.voyager_profiles(id) on delete cascade,
  title text not null,
  body text not null,
  route text not null,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'sent', 'failed', 'skipped')),
  attempted_devices integer not null default 0,
  delivered_devices integer not null default 0,
  error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (campaign_id, user_id)
);

alter table public.push_campaigns
  add column if not exists requested_by_label text not null default 'unknown';

create index if not exists push_campaign_recipients_campaign_status_idx
  on public.push_campaign_recipients (campaign_id, status, id);

alter table public.push_campaigns enable row level security;
alter table public.push_campaign_recipients enable row level security;

-- Campaigns are server-managed. Architects operate them through the protected API/CLI.
revoke all on public.push_campaigns from anon, authenticated;
revoke all on public.push_campaign_recipients from anon, authenticated;
grant select, insert, update, delete on public.push_campaigns to service_role;
grant select, insert, update, delete on public.push_campaign_recipients to service_role;
grant usage, select on sequence public.push_campaign_recipients_id_seq to service_role;

-- Atomically claim a small batch so retries or concurrent workers never double-send.
create or replace function public.claim_push_campaign_recipients(
  p_campaign_id uuid,
  p_limit integer default 20
)
returns setof public.push_campaign_recipients
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.push_campaign_recipients
  set status = 'queued', processed_at = null, error = 'Recovered after an interrupted worker'
  where campaign_id = p_campaign_id
    and status = 'processing'
    and processed_at < now() - interval '10 minutes';

  return query
  with claimed as (
    select id
    from public.push_campaign_recipients
    where campaign_id = p_campaign_id and status = 'queued'
    order by id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 20), 25))
  )
  update public.push_campaign_recipients r
  set status = 'processing', processed_at = now(), error = null
  from claimed
  where r.id = claimed.id
  returning r.*;
end;
$$;

revoke all on function public.claim_push_campaign_recipients(uuid, integer) from public, anon, authenticated;
grant execute on function public.claim_push_campaign_recipients(uuid, integer) to service_role;
